//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Id { get; set; }
        public string Genre { get; set; }
        public string Name { get; set; }
        public Nullable<int> IntvertNumber { get; set; }
        public string Auth { get; set; }
        public Nullable<System.DateTime> DatеEditions { get; set; }
        public string Publisher { get; set; }
        public string PublisherPlace { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
